<div class="grid_6">
    <div class="anuncio-grande">Institucional <b>BREITHAUPT</b></div>
    <?php
    $TextosModel = new Textos_Model();
    $texto = $TextosModel->getByCodigo('Insitucional-Breithaupt');
    echo $texto['texto'];
    ?>
</div>
<div class="grid_6 margem-b">
    <img src="/storage/imagem/fachada_antiga.jpg/lojas?w=460&h=220&c=crop" alt="Fachada - Breithaupt" class="margem-b" />
</div>
<div class="clear-fix"></div>
<div class="grid_3">
    <div class="sidebar">
        <?php
        $menu = clone($this->SiteMenu());
        $categoria = $menu->findOneByLabel('O Breithaupt');
        echo $this->navigation()->menu()->renderMenu($categoria);
        ?>
    </div>
</div>