<?php
$lojas = array(
    'marechal' =>
    array(
        'titulo' => 'Jaraguá do Sul - Marechal',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 7h30m às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 7h30m às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 7h30m às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'gumercindo' =>
    array(
        'titulo' => 'Jaraguá do Sul - Gumercindo',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 7h30m às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'barra' =>
    array(
        'titulo' => 'Jaraguá do Sul - Barra',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 7h30m às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 7h30m às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 7h30m às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'autocenter' =>
    array(
        'titulo' => 'Jaraguá do Sul - Auto Center',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 8h às 19h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 8h às 19h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h30m às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'guaramirim' =>
    array(
        'titulo' => 'Guaramirim',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'joinville' =>
    array(
        'titulo' => 'Joinville',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Até às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Até às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Até às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'saobento' =>
    array(
        'titulo' => 'São Bento do Sul',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Até às 21h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Até às 21h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Até às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'canoinhas' =>
    array(
        'titulo' => 'Canoinhas',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 8h às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 8h às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 12h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h30m às 12h30m',
                'class' => 'normal',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '02/01/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '03/01/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '04/01/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '05/01/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
        )
    ),
    'canoinhasautocenter' =>
    array(
        'titulo' => 'Canoinhas - Auto Center',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 8h às 19h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 8h às 19h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 12h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h30m às 12h30m',
                'class' => 'normal',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '02/01/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '03/01/2014',
                'dia' => 'Sábado',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '04/01/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '05/01/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
        )
    ),
    'mafra' =>
    array(
        'titulo' => 'Mafra',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 8h às 21h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 8h às 21h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Das 8h30m às 13h30m',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 13h',
                'class' => 'normal',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '02/01/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Das 13h30m às 18h',
                'class' => 'normal',
            ),
            array(
                'data' => '03/01/2014',
                'dia' => 'Sábado',
                'texto' => 'Das 8h30m às 12h30m',
                'class' => 'normal',
            ),
        )
    ),
    'balcam' =>
    array(
        'titulo' => 'Balneário Camboriu',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 16h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'itajai' =>
    array(
        'titulo' => 'Itajaí',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 8h às 12h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
    'bruque' =>
    array(
        'titulo' => 'Brusque',
        'horarios' => array(
            array(
                'data' => '22/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Das 7h30m às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '23/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Das 7h30m às 20h',
                'class' => 'normal',
            ),
            array(
                'data' => '24/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Das 7h30m às 12h',
                'class' => 'normal',
            ),
            array(
                'data' => '25/12/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '26/12/2014',
                'dia' => 'Sexta-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '27/12/2014',
                'dia' => 'Sábado',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '28/12/2014',
                'dia' => 'Domingo',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '29/12/2014',
                'dia' => 'Segunda-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '30/12/2014',
                'dia' => 'Terça-feira',
                'texto' => 'Horário Normal',
                'class' => 'normal',
            ),
            array(
                'data' => '31/12/2014',
                'dia' => 'Quarta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
            array(
                'data' => '01/01/2014',
                'dia' => 'Quinta-feira',
                'texto' => 'Fechado',
                'class' => 'fechado',
            ),
        )
    ),
);
?>
<h2>Selecione uma loja para verificar o seu horário de funcionamento nesse final de ano.</h2>
<select id="horarios">
    <option value=''>Selecione uma loja</option>
    <?php
    foreach ($lojas AS $key => $loja):
        ?>
        <option value="#<?php echo $key; ?>"><?php echo $loja['titulo']; ?></option>
        <?php
    endforeach;
    ?>
</select>
<style>
    #horarios{
        width: 250px;
        border: 1px solid #211061;
    }
    .horarios{
        display: none;
    }
    .horarios table{
        width: 50%;
    }
    .horarios h2{
        text-align: center;
    }
    .horarios .fechado{
        font-weight: bold;
        color: red;
    }
    .horarios td{
        border: 1px solid;
        text-align: center;
        text-align: center;
    }
    .horarios th{
        color: #211061;
        font-weight: bold;
    }
    .horarios th{
        padding: 10px;
    }
    .horarios .fechado td{
        border-color: red;
    }
</style>
<script>
    $(function () {
        $('#horarios').unbind('change').die('change').change(function () {
            var selecionado = $(this).val();
            if (selecionado) {
                $('.horarios').hide();
                $(selecionado).show();
            }
        });
    });
</script>
<?php
foreach ($lojas AS $key => $loja):
    ?>
    <div class='horarios' id="<?php echo $key; ?>">
        <table border="1">
            <thead>
                <tr>
                    <th colspan="3"><?php echo $loja['titulo']; ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($loja['horarios'] AS $horario):
                    ?>
                    <tr class="<?php echo $horario['class']; ?>">
                        <td><?php echo $horario['data']; ?></td>
                        <td><?php echo $horario['dia']; ?></td>
                        <td><?php echo $horario['texto']; ?></td>
                    </tr>
                    <?php
                endforeach;
                ?>
            </tbody>
        </table>
    </div>
    <?php
endforeach;
?>