<?php
if (!isset($this->noLayout)):
    $title = $this->model->getOption('title');
    echo $this->partial('partials/title.phtml', array(
        'title' => $title
    ));
endif;
?>
<div id="JornalTabs">
    <ul>
        <li><a href="#Dados">Jornal</a></li>
        <li><a href="/<?php echo $this->module; ?>/submodulo/Jornal-Paginas/pagina//<?php echo $this->data['id']; ?>">Páginas</a></li>
    </ul>
    <div id="Dados">
        <div class="grid_12">
            <?php echo $this->form; ?>
        </div>
    </div>
</div>
<script>
    $(function() {
        $("#JornalTabs").tabs({
            spinner: carregando,
            ajaxOptions: {
                error: function(xhr, status, index, anchor) {
                    if (status == 'error') {
                        $(anchor.hash).html('Erro ao carregar o conteúdo');
                    } else {
                        $(anchor.hash).html(carregando);
                    }
                }
            }
<?php echo (empty($this->data['id'])) ? ",disabled: [1]" : ''; ?>
        });
    });
</script>